### ISSUE TITLE
Request: pinch and rotate gestures

### ISSUE THREAD

**Issue by vitorgalvao** [Brass-Monkery/Multitouch-Bugs#1]
In trying to replace BetterTouchTool, I’ve just come across your app. It looks good, both interface-wise and icon-wise, but it doesn’t support everything I need. Here’s the gestures I use BetterTouchTool for:

* 4-finger tap
* Pinch in
* Pinch out
* Rotate left
* Rotate right

Currently, out of those only the 4-finger tap is supported, and no pinching or rotating.

It’d also be useful if we could support different gestures on a per-application basis, and disable the app when certain apps are in front, but that only matters to me if pinching and rotation are added.

**Comment by rrhanson** [comment]
I'll add the pinch and rotate gestures to the backlog. I do have a pretty good amount of gestures lined up to work on, so I can't guarantee these will get worked on really soon. If you don't mind me asking, what do you assign the pinch and rotate gestures to do? 

The per-application gesture config adds a good deal of complexity to the UI, and that's why I have shied away from it so far. It's not something that I'm opposed to, so I'll see if I can think through an elegant way to handle it.

**Comment by vitorgalvao** [comment]
In order of importance, my gestures and their translations:

* 4 finger tap: Middle click
* Pinch in: ⌘W
* Pinch out: ⌘⇧T
* Rotate left: ⌘⌥←
* Rotate right: ⌘⌥→

So with just pinching and rotating, I can interact with tabs in apps quite effectively. The reason I’d *like* per-app shortcuts (but it’s not a deal-breaker) is that certain apps (Safari) have different shortcuts for switching tabs.

Disabling the app in certain apps is a bit more relevant. [BetterTouchTool](https://folivora.ai/) negatively interacts with [Alfred](https://www.alfredapp.com/)’s Preferences, and I need to disable it. Again, not a deal-breaker, but still more important than differing shortcuts by app.

**Comment by rrhanson** [comment]
Thanks for letting me know your assigned actions. The reason I asked is because pinching and rotating can imply an analog style of input, like zooming or rotating an image (or adjusting volume or rotating through the application switcher) as opposed to a single action execution such as the keyboard shortcuts you mentioned. 

If the only per-app shortcuts you are concerned with are for switching tabs, there are some options in Multitouch for switching tabs in the frontmost application. There's the browser (e.g. "Safari | Chrome | Firefox") option for switching tabs within any of those three browsers, and there's the "Apps with tabs" option for handling more applications with tabs. It's a bit limited in that it only handles apps that I've added. Also, I need to add the list of the supported apps within Multitouch so that users are aware. Currently the "Apps with tabs" action will work with Safari, Chrome, Firefox, Terminal, iTerm, and Finder. If you have any that you want added, let me know and I can add it. The goal of Multitouch is to minimize the amount of configuration that the user has to do, but still provide powerful capabilities. 

I can see what you mean on disabling for certain apps. I'll add that to the backlog as well.

**Comment by silvrblood** [comment]
I currently use jitouch 2 but when tried this app it was missing just one feature 

- rest one finger and tap on the left or right

you currently have rest two fingers and tap on the left or right which takes time to get used to and also i mostly use 2 fingers on the trackpad

**Comment by rrhanson** [comment]
Thanks! I've had other users recommend that same gesture. I had held off on that one initially because it felt a little too easy to accidentally execute, but I'll look at adding it in soon.

**Comment by rrhanson** [comment]
@silvrblood, Multitouch v1.4.0 now has the rest one finger and tap on the left or right gestures. I still think it's a little too easy to accidentally execute, so I might adjust it a little.

Also, since we're on this thread, I just wanted to mention that I haven't forgotten about the other gestures/features originally posted here by @vitorgalvao. I'm working on a few other items and then I will be prioritizing my list of gestures again.

**Comment by silvrblood** [comment]
THANKS for adding this feature, its working great but it is accidentally selecting parts of page when I try to use it like images or some text . I have been using this feature extensively with ji touch 2  for a year or so and I can assure you I don't accidentally trigger this action. Also after using your app for a week its energy impact rose more than 2.5 , it started with 0.69 on my MacBook Pro.

**Comment by rrhanson** [comment]
Thanks for trying it out so quickly and getting back to me. I'll see what I can do to improve the accidental triggering. In the meantime, there is a slider in the settings tab of the preferences window that can adjust the sensitivity of the tap, which may help with the accidental triggering. Perhaps try one notch less sensitive. That slider adjusts a window of time in which the tap will register a gesture. There's a number of aspects of a trackpad touch that I take into account when determining what is an intentional touch and what's not, so there's kind of a finesse to getting it right that I'll have to spend more time getting down.

The energy impact numbers you have, are they for "Energy Impact" or "Avg Energy Impact" or both? The numbers are directly affected by how much you are using the trackpad, and by what actions your gestures are executing. Do you have any comparable numbers for jiTouch2?

It's due time for me to run some thorough profiling again, so I'll check that out as well.

**Comment by silvrblood** [comment]
Above numbers were for AVG Energy Impact and for ji touch it ranges from 0.65 to 1.2. I tried to lower the sensitivity after which it did not work at all. Rest one finger and tap on the left or right is working great, I am able to switch tabs effortlessly but when I try to switch tab it selects some of the text or will pause the video in the current tab and then switch.

**Comment by rrhanson** [comment]
Oh, sorry for the misunderstanding. Glad to hear that you're not experiencing accidental triggering on the rest plus taps. 

On the selecting text or pausing video, I'm suspecting you have tap to click enabled. I'll make an update that handles tap to click appropriately. I don't personally use tap to click, so sometimes I overlook it. If you don't use tap to click, let me know and I'll see if I can get to the bottom of what's going on.

**Comment by silvrblood** [comment]
Thanks for the early fix. It is still selecting some of the text in the current tab but not pausing the video anymore. It is better than the last time.

**Comment by rrhanson** [comment]
Ok, I'll keep at it. I created [this bug to track it](https://github.com/Brass-Monkery/Multitouch-Bugs/issues/2).

**Comment by rrhanson** [comment]
@silvrblood, I put another fix for the [tap-to-click bug](https://github.com/Brass-Monkery/Multitouch-Bugs/issues/2) in [version 1.5.1](https://multitouch.app/downloads/multitouch1.5.1.dmg). Again, it's not officially released via the updater.

If that doesn't fix the issue you're seeing, please update [the bug](https://github.com/Brass-Monkery/Multitouch-Bugs/issues/2) with the model/year of your Mac and what gestures you have enabled in Multitouch (or email it to support@multitouch.app).

I apologize for the back and forth on this one, and I appreciate your assistance in testing it out.

**Comment by silvrblood** [comment]
Now its switching between alternate tabs, it directly switches from first tab to the third tab. Even after lowering the sensitivity it does not make much of a difference. 

Macbook pro 13 2015
I use Rest one finger and tap one finger to the right or left to switch tabs in safari or apps with tabs.

**Comment by silvrblood** [comment]
Its a great improvement. But sometimes it pauses the video like out of 50 maybe 3 to 5 times. Its a great app. Will you bring this app to App Store?

**Comment by rrhanson** [comment]
Thanks for getting back to me on this. Good to hear that there's at least some improvement. I've noticed that behavior as well, and I'll still see if I can polish it further. 

Unfortunately I'm not able to put it on the App Store because it cannot be "sandboxed". In other words, Apple won't let apps that listen to global trackpad input be listed in the store.

**Comment by LiamW** [comment]
Figured I'd post in here as I did a search and see mention of firefox.

Is it not supported anymore? Though I am using the dev version. I'm just looking for a gesture to open links in new tabs with 4 finger tap. Only shows Safari and Chrome as supported.

**Comment by rxhanson** [comment]
@LiamW I think what you want is to use “middle click” as your action. That will open links in a new tab, regardless of browser. 

I overlooked supporting the dev version of Firefox - it must use a different app bundle identifier than normal Firefox. I’ll create a task in my backlog for adding it.

**Comment by vitorgalvao** [comment]
I’m no longer interested in this issue. It doesn’t look like it’ll be done any time soon, so I bit the bullet and bought BTT’s lifetime license.

Thank you for your time. Closing.
