### ISSUE TITLE
Mojave F13 key binding to 4 finger click gesture is not working.

### ISSUE THREAD

**Issue by rodrigoreyes79** [Brass-Monkery/Multitouch-Bugs#18]
Binding a keyboard shortcut (F13) to the 4 finger click gesture is not working. The keyboard I am using does have physical F13 keys. The F13 key is mapped the screenshot tool in the test machine. The app is not crashing but the screenshot is not triggered either. F13 key does trigger the screenshot. Non keyboard biding (Go to first tab) does work as expected.

**Comment by rrhanson** [comment]
@rodrigoreyes79 
I was able to reproduce this, and I have a fix that will go out in v1.7.1 soon. Thanks for reporting it. I will post to this when it is released.

**Comment by rodrigoreyes79** [comment]
@rrhanson No  problem. Thank you.

**Comment by rrhanson** [comment]
@rodrigoreyes79 The fix for this is now released in v1.7.1, and can be found at [multitouch.app/versions](https://multitouch.app/versions). I didn't put it on the in-app update channel, so you'll have to download it from the website.
Let me know when you have a chance to verify if it is indeed fixed.

**Comment by rodrigoreyes79** [comment]
@rrhanson Confirmed fixed. Thank you!!!
