### ISSUE TITLE
Add "One finger middle axis click" action

### ISSUE THREAD

**Issue by theamnesic** [Brass-Monkery/Multitouch-Bugs#19]
Hi!

Is it possible to add some One Finger options for the Magic Mouse, in particular the awesome  MagicPrefs "One finger middle axis click" option?

Thanks!

— G

**Comment by rrhanson** [comment]
Sure thing on the "One finger middle axis click". Any others that you feel strongly about?

**Comment by rrhanson** [comment]
I added an initial cut at the "One finger middle axis click" gesture in [v1.7.2](https://multitouch.app/versions). I didn't add anything for adjusting the axis width, like in MagicPrefs, but I will keep that in mind when I am changing up some of the UI to accommodate more per gesture settings in the future.

Let me know how it works, or if there's any adjustments that need to be made.

**Comment by Jeronimystro** [comment]
Hi @rrhanson ! That was a quick turnaround. Awesome! This is exactly what I need to enable the very common 'orbit' [your view] functionality in CAD software with my Magic Mouse (1). I've downloaded the trial of your software, but I can't get this 'middle click' function to work. (I'm working in Vectorworks on High Sierra). 

Do I need to affect permissions or anything? I've installed it on a secondary login account with admin permissions. 

How is 'middle-click' conveyed to a program? Is it natively supported in macOS? 

Thanks!

**Comment by rrhanson** [comment]
@Jeronimystro 
Thanks for checking out Multitouch. A couple of questions to make sure that we can narrow things down.

Is the "middle click" function that isn't working the **gesture:** "one finger middle axis click", or is it the the **action:** "Middle Click" that can be configured under the "Click" selection? 
If you don't mind playing around with other gestures/actions and verifying which of these is causing the problem, that would be great. If it's the action causing the problem, does it at least open a link in a new tab on a browser or close a browser tab that the cursor is over? If so, then at least we should be able to narrow this down to something specific to the middle mouse click behavior in your CAD software. 

> How is 'middle-click' conveyed to a program? Is it natively supported in macOS?

The middle click action is a programmatic execution of the middle mouse button that would be physically located on a mouse with the middle mouse button (or scrollwheel). This should be interpreted by macOS and any app in the identical way that an actual middle mouse click would be interpreted. Once fired, there's actually no way that I know of to differentiate the two types clicks - one created programmatically vs one created by an actual middle mouse button.

Permissions on High Sierra shouldn't be an issue. On Mojave, you would have to authorize Multitouch with Accessibility.

**Comment by Jeronimystro** [comment]
Thanks for your attention and the insight above! 

I am trying to use (and-so configured) the One Finger > Click > 'Middle Mouse Click.'  - I'm sorry but despite close inspection I can't discern any reference to 'gesture' commands for the 'One Finger' options. The only thing I see relating to gestures are the tap or swipe options available in the two-or-more finger sections. I'm using a Magic Mouse (1) not the Magic Trackpad in case that needs clarifying. I have a screenshot for you but don't see any insert/upload options here. (Novice on GitHub)

I thought I'd be thorough and test both click types you mentioned, but given that I couldn't figure their difference thought I'd restart my Mac and then test every single function in the One Finger set: None of them work for me. I tested a few from the two finger categories all of which worked.

**Comment by rrhanson** [comment]
@Jeronimystro 
Thanks for digging into this further and providing some additional info. If you don't mind, I have a few more questions to clarify a little further and make sure I have a good understanding of what you've tried.
- It sounds like no matter what action you picked for the "One finger center axis click", the action was not fired?
- When you tried a two finger gesture on the Magic Mouse (like rest one finger and tap one to the left or right), the middle click (or other action) was fired?

If both of those are true, then it would appear that the "One finger center axis click" gesture just isn't working for you. I'm not really sure why that would be the case, so I'll put together a debug build if you are willing to run it and send me the logs.

A minor point to clarify is that the "One finger center axis click" is the only one finger gesture that I have for the Magic Mouse currently. I'm not sure if I had confused you on that in my previous comment. 

Thanks for your patience. Sorry it's not just working out of the box for you.

**Comment by rrhanson** [comment]
@Jeronimystro 
Alright, I figured out what the issue was. I released[ v1.7.3](https://multitouch.app/versions) with the fix. Turned out to be a silly mistake on my part. Sorry for putting you through all that work to test things out. I really appreciate your help though!

Let me know if it's working as you would expect now, or if you experience any other issues.

All the best,
Ryan

**Comment by rrhanson** [comment]
@Jeronimystro 
Thanks for your thorough testing and positive feedback! Much appreciated. Here's some more background in response to your observations.

> The trigger gets activated, but it occurs on 'button-up' instead of 'button-down'

I actually just removed a preference checkbox on the settings for specifically this behavior in v1.7.1. As you've noticed, I lean pretty dramatically toward simplification and that's why I ended up pulling this. It's kind of a confusing thing to communicate to a user and I had thought that most people probably didn't care to use it. The reason it was a checkbox to begin with and not default functionality is because this functionality was shared with the trackpad, and tap to click on the trackpad butchers this click syncing behavior. Detecting if tap to click is enabled for users requires root access for an app. With that said, I can add it back in as the default behavior for the magic mouse since tap to click is no longer a preference in system preferences for the magic mouse. 

You can enable the setting for syncing up and down click execution in the current version of Multitouch by executing the following command in Terminal and restarting Multitouch:

`defaults write com.brassmonkery.Multitouch clickSync -int 1`

When this setting is enabled for a click based gesture and action combination, the down click will be intercepted, and the programmatic down click will be executed. When the up click occurs, it is also intercepted and the programmatic up click gets executed. In my quick testing with the magic mouse middle click with middle axis click gesture, note that the mouse drag is still executed as though it is the original mouse button (left click), so this might not work 100% in a CAD program as-is if you rely on middle clicking then dragging. I'll add fixing this as a to-do item when I revisit adding back in click syncing behavior.

> I noticed an issue when populating the 'Type Shortcut' field for Keyboard Shortcut

This is one that I get a lot of emails about. Cmd+Q, Cmd+W, and Cmd+tab are available as options in the dropdown under the "Keypress" category. Cmd+Q and Cmd+W are keyboard shortcuts that I could adjust the app to handle better, it would just be a matter of overriding the default behavior of the app. Making this better is on my to-do list, I just haven't gotten around to it yet. I've considered making an alternate keyboard shortcut input that would allow a user to input keyboard shortcuts in a different way to handle the ones that are out of the control of the app, like spotlight search (cmd+space) or cmd+tab. I've had some users with various shortcuts that this keyboard shortcut recorder that I use just can't handle.

> “Rest two fingers on the mouse and click the RIGHT finger.”
“Rest two fingers on the mouse and click the LEFT finger.”

I like these suggestions, too. I'll add those to my to-do. 

I'm going to go ahead and close out this github issue for housekeeping, but definitely feel free to open up another issue for anything - suggestions, bug, questions etc. 

Thanks!
-Ryan
