### ISSUE TITLE
Add three and four finger swipes, up/down/left/right

### ISSUE THREAD

**Issue by melefabrizio** [Brass-Monkery/Multitouch-Bugs#20]
Multitouch should support swipes with three and four fingers in all directions, so you can e.g. swipe down with three fingers to close a window (cmd+W).

**Comment by lorenzofanchi** [comment]
this sounds like a great idea, guess you'd need to find a way to check which swipes are currently in use by the system?

**Comment by rxhanson** [comment]
I had initially avoided adding these gestures in mainly because they conflict with the built-in gestures, of course, and the initial intent of the Multitouch app was not to override Apple's behavior but to work alongside it. These are the most asked for gestures, though, so it makes sense to work on these next. 

I had put decent amount of thought into this a while back. I've always felt like an analog approach to swipes make more sense while most actions in the app are just triggered without an analog aspect. To me it makes the swipe gesture feel "cheap" compared to Apple's gestures since Apple's behave in an analog way, but I completely understand the desire to be able to customize the swipes. 

@lorenzofanchi, another aspect that I disliked about implementing these is that checking which swipes are currently in use is kind of... not ideal. I can check the system settings to see the configuration, but I can't get notified if the settings change and I can't change the configuration. It's kind of crappy to poll the settings all the time, so it ultimately turns into just communicating to a user that they have to manage the settings in System Preferences if they want things to work properly. This makes for a clunky user experience, but that's the tradeoff. 

It'll still take a bit of time to get this off the ground (sorry everyone who's already waited 6 months), as I'm working getting another release of [Cloudwing](https://cloudwing.app) out the door at the moment.

**Comment by rxhanson** [comment]
Ok, I have a beta out with my initial cut at the three finger right and left swipes. You can grab it at [https://multitouch.app/versions](https://multitouch.app/versions), it's version 1.10.2 (Beta).

@lorenzofanchi, if you don't mind giving it a try, let me know how the sensitivity is for the swipes since I know that your MBP trackpad behaves differently from mine. The sensitivity segmented control in the preferences pane is tied to the sensitivity for these two swipe gestures, but I'm guessing we'll probably have to tweak the values once you test it out.

I don't have anything in place yet for checking for existing Apple gestures that would conflict, so that will be added in once I pull this out of Beta.

**Comment by lorenzofanchi** [comment]
@rxhanson thanks for pushing this out so fast. Already installed the beta, will try extensively and report back!

**Comment by rxhanson** [comment]
@lorenzofanchi, awesome, looking forward to hearing your feedback.

**Comment by rxhanson** [comment]
I've pushed out another beta for this (1.10.3 on [https://multitouch.app/versions](https://multitouch.app/versions)).

I didn't touch the three finger right/left swipes from last beta, but I added the three finger up/down swipes. They are still a ways off from where I'd like them to be for an official release. Notably:

- The sensitivity is a little bit off compared to the Apple gestures. I'm comparing to the "instantaneous" quick swipe up or down, not the slow Apple swipe up/down. I don't intend to implement the slow swipes since Multitouch actions are instantaneous.
- The scroll behavior is the main pain point that's going to take some time to get right. In these betas, I haven't done anything to prevent scrolling from happening. Apple's scroll filtering behavior happens at a lower level than where I have access to, and it's actually pretty complicated behavior. I haven't checked what other gesture apps do, but I'm sure that some of them don't bother rejecting the scroll or do things differently. I might explore different ways to handle this, but letting the scroll events occur definitely doesn't feel right when there's an app that scrolls under the cursor.

**Comment by rxhanson** [comment]
Version 1.11 now has three and four finger swipes with left, down, up, and right. Note that the scroll behavior I commented on is still present, as I couldn't find a good way to prevent scrolling and still feel right. I wrote about it in more detail in a [blog post](https://medium.com/ryan-hanson/custom-three-and-four-finger-swipes-25904cba3749).

I'm going to go ahead and close this one out. If any issues are found or adjustments need to be made, please make a new issue for it.
