### ISSUE TITLE
Works on external wireless trackpad but not on MBP internal trackpad

### ISSUE THREAD

**Issue by DrorCohenCC** [Brass-Monkery/Multitouch-Bugs#27]
Hey there! I got a new laptop and moved over to Multitouch from Magicprefs after it let me know it's no longer supported. Multitouch works great when I use my external trackpad but the same gestures don't work at all when I try them from the MBP internal trackpad. I got a new 13" MBP with TB running on Mojave.
Currently there's only one gesture I set up which is Three Finger Click -> Middle Mouse Click

![image](https://user-images.githubusercontent.com/349247/48674005-7bb26500-eb50-11e8-9d75-ef8cb4558053.png)

Any help will be greatly appreciated!

**Comment by rxhanson** [comment]
Thanks for trying out Multitouch! Sorry you’re having issues. At a start, please select Help -> Contact Support in the Multitouch menu, and send us an email with the pre-filled info there. That will tell us the devices that Multitouch recognizes, so we can at least confirm that your internal trackpad is recognized. 

Also, you could try selecting the checkbox for “Avoid private frameworks” in the settings panel. This changes where multitouch obtains the touch data from, and could fix your isssue. It’s kind of odd, but not all macs behave the same way always with touch detection, despite having the same specs.

**Comment by DrorCohenCC** [comment]
Thanks @rxhanson for the help. I just submitted the email from the "Contact Support" feature, but here is its output for your convenience:

```
macOS: Version 10.14.1 (Build 18B75)
Model: MacBookPro15,2
Devices: ["magicTrackpad"]
Multitouch Configuration: {"threeForce":{"type":3,"action":300},"threeClick":{"type":3,"action":300}}
```
Let me know if this helps.
I also tried turning on “Avoid private frameworks” and restarting Multitouch but nothing seems to have changed.

By the way, it would be nice if for the "Contact Support" we wouldn't need to use Mac OS email client. If you're not using it, it kind of forces you to sync your account just to fetch these details.

Thanks!

**Comment by rxhanson** [comment]
Thanks @DrorCohenCC, I got the email. "Contact Support" uses a "mailto" link to open your default mail application, which defaults to the macOS email client if you don't change it. I can see how that would be annoying, as I don't use that mail client either. I'll throw something in to make it so that's not necessary to obtain that info.

As you could probably see, Multitouch is not recognizing your internal trackpad. Unfortunately, Apple makes it kind of tricky to "keep up" with finding their internal trackpads because they can change around identifiers for them. It's hard to create a generic case that will catch everything, and it seems that it somehow slipped through the logic that I have.

In order to more quickly make sure my logic will catch your trackpad and hopefully newer ones, it would be really helpful if you sent me the IO registry info from your machine. If you don't mind, you can grab it by running the following command in Terminal:
`ioreg -p IOUSB -w0 -l`

This command will output information on all of the USB devices connected to your machine. You can send me the entire output if you want, but I am only concerned with the information pertaining to the internal trackpad. If you do send this to me and prefer to email it, you can send it to support@multitouch.app.

Here's an example of what I'm after:

> +-o Apple Internal Keyboard / Trackpad@06300000  <class AppleUSBDevice, id 0x10000029b, registered, matched, active, busy 0 (1 ms), retain 18>
>     |   {
>     |     "sessionID" = 1381161037
>     |     "iManufacturer" = 1
>     |     "bNumConfigurations" = 1
>     |     "idProduct" = 566
>     |     "bcdDevice" = 144
>     |     "Bus Power Available" = 250
>     |     "USB Address" = 1
>     |     "bMaxPacketSize0" = 8
>     |     "iProduct" = 2
>     |     "iSerialNumber" = 0
>     |     "bDeviceClass" = 0
>     |     "Built-In" = Yes
>     |     "locationID" = 103809024
>     |     "bDeviceSubClass" = 0
>     |     "bcdUSB" = 512
>     |     "USB Product Name" = "Apple Internal Keyboard / Trackpad"
>     |     "PortNum" = 3
>     |     "non-removable" = "yes"
>     |     "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>     |     "bDeviceProtocol" = 0
>     |     "IOUserClientClass" = "IOUSBDeviceUserClientV2"
>     |     "IOPowerManagement" = {"DevicePowerState"=2,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
>     |     "kUSBCurrentConfiguration" = 1
>     |     "Device Speed" = 1
>     |     "USB Vendor Name" = "Apple Inc."
>     |     "idVendor" = 1452
>     |     "ExtendedData" = (50399521,50465057)
>     |     "IOGeneralInterest" = "IOCommand is not serializable"
>     |     "IOClassNameOverride" = "IOUSBDevice"
>     |   }

Another thing that would help is if you tried disconnecting your external trackpad, then restarted Multitouch. If Multitouch does not detect any devices through Apple's supported means, it will leverage a private framework after a few seconds to attempt to find any devices. If this works and your trackpad is found, I can at least improve my logic further to fall back to the private framework if it knows that it is running on a macbook and doesn't find an internal trackpad.

Thanks!

**Comment by DrorCohenCC** [comment]
Thanks @rxhanson, I just sent you the output via email. I tried disconnecting the external trackpad and restarting multitouch and it did work! However if I restart Multitouch once more when the external trackpad is connected, this doesn't work again. 

I'll work it out in the meanwhile but please update when a fix is out. Many thanks for the help!

**Comment by rxhanson** [comment]
Thanks for your patience! 
Multitouch v1.8 has the fix for this, and is now available as an in-app update or for download here: [https://multitouch.app/versions](https://multitouch.app/versions).

If you don't mind, there's one last thing that would help me further for these types of issues in the future. I've added in a button on the About window (Help -> About Multitouch) for grabbing the debug info that was previously only accessible via Contact Support. If you could send me that info one more time after the update, that would be great. 

I've updated this info to contain two numbers for each device, gathered by the different ways to figure out what devices are connected. 

Let me know if you come across any further issues.

**Comment by DrorCohenCC** [comment]
Awesome! This seems to work great. Really appreciate the fast turnaround! 💯 

The new debug info button works and I'll send over the clipboard information over email. 

Thanks!

**Comment by rxhanson** [comment]
Gonna close this one out, but be sure to let me know if you come across anything else. Thanks for sending the info! Much appreciated.

**Comment by rxhanson** [comment]
@l3iodeez, I'll see what I can do. It's a surprising challenge to ensure that all MacBook pros deliver touch data (from Apple's supported or private frameworks) to Multitouch. 

I received your correspondence with Paddle support regarding a refund and went ahead and initiated the refund.

**Comment by l3iodeez** [comment]
@rxhanson Thanks for the reply! If we can get this resolved I am happy to re-purchase (I don't know how people use macs without middle click).

**Comment by rxhanson** [comment]
@l3iodeez, I've noticed that a lot of people end up looking at Multitouch for just the middle click functionality. A free option that looks like still works for a lot of people (despite being unmaintained), is https://github.com/cl3m/MiddleClick.
I was going to break out the middle click functionality from Multitouch and make that a separate product, but then I found that repo. Might be worth a try if you're a developer.
