### ISSUE TITLE
Can not record a keyboard shortcut like cmd + tab

### ISSUE THREAD

**Issue by quanru** [Brass-Monkery/Multitouch-Bugs#29]

**Comment by rxhanson** [comment]
System shortcuts like “cmd+tab” that can’t be recorded by the shortcut recorder can be found under the “Keypress” category.

I’ve been meaning to at least add some text explaining this next to the keyboard shortcut recorder, but keep forgetting to do it.

Alternatively, I have wanted to implement my own keyboard shortcut recorder (instead of using MASShortcut), but that’s a pretty time consuming task that isn’t as high priority as some of the other tasks.

**Comment by quanru** [comment]
shielding existing shortcut function when record a shortcut

**Comment by rxhanson** [comment]
I'm going to close out this bug since there is a workaround. I have a backlog item for the alternate keyboard shortcut recorder, so I won't forget.

**Comment by austinarchibald** [comment]
Sorry exactly how do you do this in Multitouch? I want to run a script that asks for confirmation before quitting Safari, similar to [this](https://medium.com/macoclock/how-to-get-confirmation-alert-before-quitting-safari-on-macos-f76aef37477e), but with Multitouch instead. Can't record ⌘Q (for Safari only) while in preferences because it quits Multitouch. Thanks!

**Comment by rxhanson** [comment]
@austinarchibald There's not really a good way in Multitouch to prompt before quitting Safari, and actually, in my opinion the best way to do that is following those steps you linked. Having cmd+q as a keyboard shortcut mapped by Multitouch could only be done by modifying the underlying defaults preferences, and then you'd have to configure that keyboard shortcut execute a script via bash command to do the prompt for safari only. That's unfortunately a good bit more complicated than those steps.
