### ISSUE TITLE
rest one finger and swipe down with one to the left is conflicted with rest one finger and tap one finger to the left

### ISSUE THREAD

**Issue by quanru** [Brass-Monkery/Multitouch-Bugs#33]
![image](https://user-images.githubusercontent.com/11739753/49097251-58ea2400-f2a7-11e8-9012-0628f4cfc5b8.png)

**Comment by rxhanson** [comment]
Thanks for letting me know. I'm still trying to work out the sensitivity of the swipe vs the tap so they can coexist.

On another topic, I recommend trying "Apps with tabs" -> "Switch tabs left" & "Switch tabs right" if you haven't already. It looks like that's what you're trying to do with these configurations, and that might work better for you.

Also, I love the pink.

**Comment by lorenzofanchi** [comment]
In my testing too this has happened sporadically. Maybe the two finger swipe would be less prone to be misinterpreted as a tap?

**Comment by rxhanson** [comment]
I still think there can be a good balance that can be reached with just the one fixed + one swipe vs the one fixed + one tap, it just might take a couple of iterations to get it right. It comes down to how much movement is allowed to be translated as a tap vs how much is translated as a swipe and which gesture has precedence if there is overlap in the amount of movement tolerated for each. Both gestures need to be modified some in order to better account for this. I take it that you are thinking you are executing a swipe, but a tap is also executed at the same time? 

I'm still not a huge fan of the one fixed + two finger swipe primarily because I still see Multitouch (hopefully) as an app that coexists really well with Apple's default gestures, and I always end up executing a three finger swipe up/down when I execute the one fixed + two finger. @lorenzofanchi, do you disable the Apple three finger swipe up/down in order to use that gesture with JiTouch?

**Comment by lorenzofanchi** [comment]
@rxhanson I never had to disable any Apple-specific gestures, but like you mentioned in the other thread, there might be differences between trackpads that could influence sensitivity to triggering unintended gestures?

**Comment by rxhanson** [comment]
Good to know. Let me see how well I can get the one plus one gestures to perform, and we'll take it from there.

**Comment by quanru** [comment]
i found it was not conflicted, it just won't trigger the function, but it did trigger the action.

**Comment by rxhanson** [comment]
@quanru, please try with the latest version: [1.8.3](https://multitouch.app/versions) and let me know if you are still having issues.

@lorenzofanchi, with the updated algorithm mentioned in https://github.com/Brass-Monkery/Multitouch-Bugs/issues/24, swipes and taps should be rather independent. In my testing, this behaved as I expected, but you'll have to let me know if you still experience conflicted behavior between these two gestures.

**Comment by quanru** [comment]
@rxhanson it's ok now

**Comment by rxhanson** [comment]
I'm going to go ahead and close this one out, but it can always be reopened or another bug can be opened if anyone continues to experience conflicting behavior between the tap and swipe gestures.
