### ISSUE TITLE
UI issue selecting triggers

### ISSUE THREAD

**Issue by lorenzofanchi** [Brass-Monkery/Multitouch-Bugs#39]
There's some unintuitive behavior in the trigger selection interface. After opening the action selection UI for a particular trigger, I can still select other triggers in the main window. However, the action selection window is not updated accordingly. See video.

https://streamable.com/7wkjg

This could be by design, but personally it seems more intuitive the update the actions menu when selecting a different trigger. Why else would I be selecting it? ;)

Just my 2 cents...

**Comment by rxhanson** [comment]
This change was actually due to my frustration with how annoying it was to just delete a gesture configuration. When I'm testing out changes to the app, I'm constantly adding and removing gestures, and the UI felt wrong to me. This UI change definitely feels better for deleting gestures in my opinion, but I get what you're saying and I think you're right in terms of user expectation. Double clicking a gesture will bring up the config popover if you don't want to travel all the way to the arrow to open it.

I'm glad you said something, as it makes me re-evaluate my thought process on that. I'll see if I can build a middle ground that allows me to delete easier. Maybe I'll change it back to the previous behavior but make the arrow an X and have it delete the gesture.

**Comment by rxhanson** [comment]
Closing this one out, since the updated behavior is now officially released in v1.11.
