### ISSUE TITLE
App Switcher Gesture

### ISSUE THREAD

**Issue by IndigoHomme** [Brass-Monkery/Multitouch-Bugs#40]
Feature Request:
I am using a four finger tap to invoke App Switcher.
On four finger release the band of app icons appears.
Using two fingers I run the selector along the band and stop at the selected app.
Coming from BetterTouchTool I miss the two finger lift switching to the selected app.
Please add this.
I have two choices with Multitouch: either hit Return or using a single finger bring the cursor to the selected App and tap.
Thanks.

**Comment by rxhanson** [comment]
Thanks for posting this - I was unaware that BTT did this. Other gestures in Multitouch that don't result in an instantaneous removal of touches have this behavior so it makes sense to add this behavior in for instantaneous taps and maybe other gestures like this. It should be a relatively small change, so I'll see if I can add it in soon.

As a side note, looks like the space bar also works for selecting an app.

**Comment by rxhanson** [comment]
I've added this in to a beta (v1.11.2), which can be downloaded at [https://multitouch.app/versions](https://multitouch.app/versions). When selecting the action for your four finger tap, select Application Switcher -> **Open, then auto-close**. 

If you get a chance to try it out, let me know if you come across any issues with it.

**Comment by rxhanson** [comment]
This has since been released, and is in the current version 1.13. Feel free to create a new issue, or reopen this one if there are any problems with it.

**Comment by jaustin** [comment]
Wasn't sure whether you'd like a new issue for this, or re-open this one. As far as I can see, as you've implemented this feature, it only works for a four finger 'tap', not swipes?

One of the really neat things about being able to assign this to a four finger swipe is that (at least in BTT's implementation) you can:
 * Swipe and release all fingers to switch immediately between the two most recent applications (equivalent to tapping ⌘+tab)
 * Swipe and keep two fingers down to scroll between applications. Release two all fingers to 'select' the currently highlighted app. (equivalent to holding down ⌘ then tapping tab)

I haven't found a way to emulate this behaviour with Multitouch yet. (And in fact, I think it might be why BTT has a preference to use its own App switcher?)

FWIW, I think this behaviour was introduced in Snow Leopard as the default four finger gesture behaviour, then reverted in a later macOS version - and some people like me have been clinging onto it since!

**Comment by rxhanson** [comment]
@jaustin thanks, I went ahead and moved this to https://github.com/rxhanson/Multitouch-Community/issues/124.
